# Generated by Django 4.0.3 on 2022-03-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_categoria_activo_categoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8),
        ),
    ]
