# Generated by Django 4.0.3 on 2022-03-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, default=1, help_text=' en dólares', max_digits=2)),
                ('peso', models.PositiveIntegerField(default=0, help_text=' en Libras')),
                ('tipo', models.CharField(choices=[('Virtual', 'Virtual'), ('Fisico', 'Fisico')], default='Fisico', max_length=7)),
                ('url_download', models.URLField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Libros',
            },
        ),
    ]
