# Generated by Django 4.0.3 on 2022-03-13 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_libro'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='libro',
            unique_together={('nombre', 'tipo')},
        ),
    ]
