# Generated by Django 4.0.3 on 2022-03-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_libro_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.FloatField(default=1, help_text=' en dólares'),
        ),
    ]
