# Generated by Django 4.0.3 on 2022-03-13 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_libro_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progenitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('padre', models.CharField(max_length=50)),
                ('madre', models.CharField(max_length=50)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.persona')),
            ],
            options={
                'verbose_name_plural': 'Progenitores',
            },
        ),
    ]
