# Generated by Django 4.0.3 on 2022-03-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_employee_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPadreHijo',
            fields=[
                ('idpadre', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrepadre', models.CharField(max_length=50)),
                ('idhijo', models.IntegerField()),
                ('nombrehijo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'view_padrehijo',
                'managed': False,
            },
        ),
    ]
