# Generated by Django 4.0.3 on 2022-03-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_viewpadrehijo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoNombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nuevo_nombre',
            },
        ),
    ]
