# Generated by Django 4.0.3 on 2022-03-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_nuevonombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevonombre',
            name='a',
            field=models.CharField(db_column='otro_nombre', default='', max_length=50),
        ),
    ]
