# Generated by Django 4.0.3 on 2022-03-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_nuevonombre_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='slug',
            field=models.SlugField(default='', max_length=60),
        ),
    ]
