# Generated by Django 4.0.3 on 2022-04-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_categoria_descripcion_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='estado',
            field=models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')], default='Activo', max_length=8),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')], default='Activo', max_length=8),
        ),
        migrations.AlterField(
            model_name='libro',
            name='estado',
            field=models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')], default='Activo', max_length=8),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado',
            field=models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')], default='Activo', max_length=8),
        ),
        migrations.AlterField(
            model_name='progenitor',
            name='estado',
            field=models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')], default='Activo', max_length=8),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='estado',
            field=models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')], default='Activo', max_length=8),
        ),
    ]
